export const categoryList = [
  {
    id: 1,
    value: 'crianças',
    label: '👶 crianças',
  },
  {
    id: 2,
    value: 'idosos',
    label: '👴 idosos',
  },
  {
      id: 3,
      value: 'pcd',
      label: '👩‍🦽 pcd',
    },
  {
      id: 4,
      value: 'pets',
      label: '🐶 pets',
    },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1⭐',
  },
  {
    id: 2,
    value: '2',
    label: '2⭐',
  },
  {
    id: 3,
    value: '3',
    label: '3⭐',
  },
  {
    id: 4,
    value: '4',
    label: '4⭐',
  },
  {
    id: 5,
    value: '5',
    label: '5⭐',
  },
];

export const dataList = [
  {
    id: 1,
    name: 'carlos eduardo',
    localization: 'minas gerais',
    category: 'idosos',
    description: 'cuidador experiente com atividades acertivas.',
    rating: 5,
    price: 80,
    coverSrc: '',
  },
  {
      id: 2,
      name: 'mariana silva',
      localization: 'são paulo',
      category: 'crianças',
      description: 'cuidadora experiente de crianças com atividades divertidas e educacionais.',
      rating: 4,
      price: 70,
      coverSrc: '',
    },
    {
      id: 3,
      name: 'josé santos',
      localization: 'campinas',
      category: 'idosos',
      description: 'dedicado ao cuidado de idosos com carinho e atenção personalizada.',
      rating: 5,
      price: 90,
      coverSrc: '',
    },
    {
      id: 4,
      name: 'ana paula',
      localization: 'são bernardo do campo',
      category: 'pcd',
      description: 'assistência especializada para pessoas com deficiência, focada na autonomia.',
      rating: 4,
      price: 75,
      coverSrc: '',
    },
    {
      id: 5,
      name: 'ricardo oliveira',
      localization: 'osasco',
      category: 'pets',
      description: 'amante de animais de estimação, cuida do seu pet com amor e dedicação.',
      rating: 5,
      price: 60,
      coverSrc: '',
    },
    {
      id: 6,
      name: 'carla pereira',
      localization: 'santos',
      category: 'crianças',
      description: 'educação infantil de qualidade para um desenvolvimento saudável.',
      rating: 5,
      price: 85,
      coverSrc: '',
    },
    {
      id: 7,
      name: 'pedro rocha',
      localization: 'jundiaí',
      category: 'idosos',
      description: 'companhia e assistência para idosos com cuidado e respeito.',
      rating: 4,
      price: 88,
      coverSrc: '',
    },
    {
      id: 8,
      name: 'isabela costa',
      localization: 'ribeirão preto',
      category: 'pcd',
      description: 'atendimento personalizado para pessoas com deficiência, focado na inclusão.',
      rating: 5,
      price: 70,
      coverSrc: '',
    },
    {
      id: 9,
      name: 'joão ferreira',
      localization: 'são josé dos campos',
      category: 'pets',
      description: 'cuidados atenciosos para animais de estimação, garantindo bem-estar.',
      rating: 5,
      price: 65,
      coverSrc: '',
    },
    {
      id: 10,
      name: 'caroline lima',
      localization: 'sorocaba',
      category: 'crianças',
      description: 'aventuras e aprendizado para crianças em um ambiente seguro e divertido.',
      rating: 5,
      price: 80,
      coverSrc: '',
    },
    {
      id: 11,
      name: 'marcos almeida',
      localization: 'santo andré',
      category: 'idosos',
      description: 'apoio emocional e físico para idosos, promovendo qualidade de vida.',
      rating: 5,
      price: 95,
      coverSrc: '',
    },
    {
      id: 12,
      name: 'patrícia fernandes',
      localization: 'mogi das cruzes',
      category: 'pcd',
      description: 'assistência inclusiva para pessoas com deficiência, respeitando suas necessidades.',
      rating: 4,
      price: 78,
      coverSrc: '',
    },
    {
      id: 13,
      name: 'roberto xavier',
      localization: 'são caetano do sul',
      category: 'pets',
      description: 'amigo dos animais e cuidador dedicado para o seu pet.',
      rating: 5,
      price: 70,
      coverSrc: '',
    },
    {
      id: 14,
      name: 'juliana rodrigues',
      localization: 'piracicaba',
      category: 'crianças',
      description: 'aprendizado lúdico e atividades criativas para crianças de todas as idades.',
      rating: 4,
      price: 75,
      coverSrc: '',
    },
    {
      id: 15,
      name: 'antônio nunes',
      localization: 'diadema',
      category: 'idosos',
      description: 'acolhimento e cuidado para idosos, promovendo qualidade de vida.',
      rating: 5,
      price: 90,
      coverSrc: '',
    },
    {
      id: 16,
      name: 'fernanda mendes',
      localization: 'itaquaquecetuba',
      category: 'pcd',
      description: 'apoio individualizado para pessoas com deficiência, valorizando sua independência.',
      rating: 4,
      price: 80,
      coverSrc: '',
    },
    {
      id: 17,
      name: 'gustavo castro',
      localization: 'taboão da serra',
      category: 'pets',
      description: 'cuidados amorosos e brincadeiras para seu pet durante sua ausência.',
      rating: 5,
      price: 65,
      coverSrc: '',
    }
];
