export const categoryList = [
    {
      id: 1,
      value: 'Crianças',
      label: '👶 Crianças',
    },
    {
      id: 2,
      value: 'Idosos',
      label: '👴 Idosos',
    },
    {
        id: 3,
        value: 'PcD',
        label: '👩‍🦽 PcD',
      },
    {
        id: 4,
        value: 'Pets',
        label: '🐶 Pets',
      },
  ];
  
  export const ratingList = [
    {
      id: 1,
      value: '1',
      label: '1⭐',
    },
    {
      id: 2,
      value: '2',
      label: '2⭐',
    },
    {
      id: 3,
      value: '3',
      label: '3⭐',
    },
    {
      id: 4,
      value: '4',
      label: '4⭐',
    },
    {
      id: 5,
      value: '5',
      label: '5⭐',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      name: 'Carlos Eduardo',
      localization: 'Guarulhos',
      category: 'Idosos',
      description: 'Cuidador experiente com atividades acertivas.',
      rating: 5,
      price: '80/h',
      coverSrc: '',
    },
    {
        id: 2,
        name: 'Mariana Silva',
        localization: 'São Paulo',
        category: 'Crianças',
        description: 'Cuidadora experiente de crianças com atividades divertidas e educacionais.',
        rating: 4,
        price: '70/h',
        coverSrc: '',
      },
      {
        id: 3,
        name: 'José Santos',
        localization: 'Campinas',
        category: 'Idosos',
        description: 'Dedicado ao cuidado de idosos com carinho e atenção personalizada.',
        rating: 5,
        price: '90/h',
        coverSrc: '',
      },
      {
        id: 4,
        name: 'Ana Paula',
        localization: 'São Bernardo do Campo',
        category: 'PcD',
        description: 'Assistência especializada para pessoas com deficiência, focada na autonomia.',
        rating: 4,
        price: '75/h',
        coverSrc: '',
      },
      {
        id: 5,
        name: 'Ricardo Oliveira',
        localization: 'Osasco',
        category: 'Pets',
        description: 'Amante de animais de estimação, cuida do seu pet com amor e dedicação.',
        rating: 5,
        price: '60/h',
        coverSrc: '',
      },
      {
        id: 6,
        name: 'Carla Pereira',
        localization: 'Santos',
        category: 'Crianças',
        description: 'Educação infantil de qualidade para um desenvolvimento saudável.',
        rating: 5,
        price: '85/h',
        coverSrc: '',
      },
      {
        id: 7,
        name: 'Pedro Rocha',
        localization: 'Jundiaí',
        category: 'Idosos',
        description: 'Companhia e assistência para idosos com cuidado e respeito.',
        rating: 4,
        price: '88/h',
        coverSrc: '',
      },
      {
        id: 8,
        name: 'Isabela Costa',
        localization: 'Ribeirão Preto',
        category: 'PcD',
        description: 'Atendimento personalizado para pessoas com deficiência, focado na inclusão.',
        rating: 5,
        price: '70/h',
        coverSrc: '',
      },
      {
        id: 9,
        name: 'João Ferreira',
        localization: 'São José dos Campos',
        category: 'Pets',
        description: 'Cuidados atenciosos para animais de estimação, garantindo bem-estar.',
        rating: 5,
        price: '65/h',
        coverSrc: '',
      },
      {
        id: 10,
        name: 'Caroline Lima',
        localization: 'Sorocaba',
        category: 'Crianças',
        description: 'Aventuras e aprendizado para crianças em um ambiente seguro e divertido.',
        rating: 5,
        price: '80/h',
        coverSrc: '',
      },
      {
        id: 11,
        name: 'Marcos Almeida',
        localization: 'Santo André',
        category: 'Idosos',
        description: 'Apoio emocional e físico para idosos, promovendo qualidade de vida.',
        rating: 5,
        price: '95/h',
        coverSrc: '',
      },
      {
        id: 12,
        name: 'Patrícia Fernandes',
        localization: 'Mogi das Cruzes',
        category: 'PcD',
        description: 'Assistência inclusiva para pessoas com deficiência, respeitando suas necessidades.',
        rating: 4,
        price: '78/h',
        coverSrc: '',
      },
      {
        id: 13,
        name: 'Roberto Xavier',
        localization: 'São Caetano do Sul',
        category: 'Pets',
        description: 'Amigo dos animais e cuidador dedicado para o seu pet.',
        rating: 5,
        price: '70/h',
        coverSrc: '',
      },
      {
        id: 14,
        name: 'Juliana Rodrigues',
        localization: 'Piracicaba',
        category: 'Crianças',
        description: 'Aprendizado lúdico e atividades criativas para crianças de todas as idades.',
        rating: 4,
        price: '75/h',
        coverSrc: '',
      },
      {
        id: 15,
        name: 'Antônio Nunes',
        localization: 'Diadema',
        category: 'Idosos',
        description: 'Acolhimento e cuidado para idosos, promovendo qualidade de vida.',
        rating: 5,
        price: '90/h',
        coverSrc: '',
      },
      {
        id: 16,
        name: 'Fernanda Mendes',
        localization: 'Itaquaquecetuba',
        category: 'PcD',
        description: 'Apoio individualizado para pessoas com deficiência, valorizando sua independência.',
        rating: 4,
        price: '80/h',
        coverSrc: '',
      },
      {
        id: 17,
        name: 'Gustavo Castro',
        localization: 'Taboão da Serra',
        category: 'Pets',
        description: 'Cuidados amorosos e brincadeiras para seu pet durante sua ausência.',
        rating: 5,
        price: '65/h',
        coverSrc: '',
      }
      
  ];